Abort while install failed

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -116,11 +116,11 @@ CORRECTMD5=`cat "$TMPDIR/fonts/NotoSansCJK.ttc.md5"`
 MD5=`md5sum "$TMPDIR/fonts/NotoSansCJK.ttc" | cut -d ' ' -f1`
 
 if [ "$CORRECTMD5" = "$MD5" ]; then
-	ui_print "- MD5 check passed. Copying fonts to system."
+	ui_print "- Copying fonts to system"
 	mkdir -p "$MODPATH/system/fonts" >&2
 	cp "$TMPDIR/fonts/NotoSansCJK.ttc" "$MODPATH/system/fonts/NotoSansCJK.ttc" >&2
 else
-	ui_print "- MD5 checked failed. Maybe you should re-download this module."
+	abort "! MD5 checked failed!"
 fi
 
 # Remove placeholder
@@ -152,18 +152,18 @@ $POSTFSDATA && cp -af $INSTALLER/common/post-fs-data.sh $MODPATH/post-fs-data.sh
 $LATESTARTSERVICE && cp -af $INSTALLER/common/service.sh $MODPATH/service.sh
 
 # migrating fonts.xml
-ui_print "- Migrating fonts.xml"
 [[ -d /sbin/.core/mirror ]] && MIRRORPATH=/sbin/.core/mirror || unset MIRRORPATH
 FILE=fonts.xml
 FILEPATH=/system/etc/
 if [ -f $MIRRORPATH$FILEPATH$FILE ]; then
-	if [ -f "$MODPATH/system/fonts/NotoSansCJK.ttc" ]; then
-	  mkdir -p $MODPATH$FILEPATH
-	  cp -af $MIRRORPATH$FILEPATH$FILE $MODPATH$FILEPATH$FILE
-	  sed -i '/<family lang=\"zh-Hans\">/,/<\/family>/ {/<\/family>/! d;/<\/family>/ s/.*/    <family lang="zh-Hans">\n        <font weight="100" style="normal" index="2">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="6">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="10">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="14">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="22">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="34">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="26">NotoSansCJK.ttc<\/font>\n    <\/family>/};/<family lang=\"zh-Hant\">/,/<\/family>/ {/<\/family>/! d;/<\/family>/ s/.*/    <family lang="zh-Hant">\n        <font weight="100" style="normal" index="3">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="7">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="11">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="15">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="23">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="35">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="27">NotoSansCJK.ttc<\/font>\n    <\/family>/};/<family lang=\"ja\">/,/<\/family>/ {/<\/family>/! d;/<\/family>/ s/.*/    <family lang="ja">\n        <font weight="100" style="normal" index="0">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="4">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="8">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="12">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="20">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="32">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="24">NotoSansCJK.ttc<\/font>\n    <\/family>/};/<family lang=\"ko\">/,/<\/family>/ {/<\/family>/! d;/<\/family>/ s/.*/    <family lang="ko">\n        <font weight="100" style="normal" index="1">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="5">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="9">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="13">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="21">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="33">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="25">NotoSansCJK.ttc<\/font>\n    <\/family>/};/^$/d' $MODPATH$FILEPATH$FILE >&2
-	fi
+  if [ -f "$MODPATH/system/fonts/NotoSansCJK.ttc" ]; then
+    ui_print "- Migrating fonts.xml"
+    mkdir -p $MODPATH$FILEPATH
+    cp -af $MIRRORPATH$FILEPATH$FILE $MODPATH$FILEPATH$FILE
+    sed -i '/<family lang=\"zh-Hans\">/,/<\/family>/ {/<\/family>/! d;/<\/family>/ s/.*/    <family lang="zh-Hans">\n        <font weight="100" style="normal" index="2">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="6">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="10">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="14">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="22">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="34">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="26">NotoSansCJK.ttc<\/font>\n    <\/family>/};/<family lang=\"zh-Hant\">/,/<\/family>/ {/<\/family>/! d;/<\/family>/ s/.*/    <family lang="zh-Hant">\n        <font weight="100" style="normal" index="3">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="7">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="11">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="15">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="23">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="35">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="27">NotoSansCJK.ttc<\/font>\n    <\/family>/};/<family lang=\"ja\">/,/<\/family>/ {/<\/family>/! d;/<\/family>/ s/.*/    <family lang="ja">\n        <font weight="100" style="normal" index="0">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="4">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="8">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="12">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="20">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="32">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="24">NotoSansCJK.ttc<\/font>\n    <\/family>/};/<family lang=\"ko\">/,/<\/family>/ {/<\/family>/! d;/<\/family>/ s/.*/    <family lang="ko">\n        <font weight="100" style="normal" index="1">NotoSansCJK.ttc<\/font>\n        <font weight="300" style="normal" index="5">NotoSansCJK.ttc<\/font>\n        <font weight="350" style="normal" index="9">NotoSansCJK.ttc<\/font>\n        <font weight="400" style="normal" index="13">NotoSansCJK.ttc<\/font>\n        <font weight="500" style="normal" index="21">NotoSansCJK.ttc<\/font>\n        <font weight="900" style="normal" index="33">NotoSansCJK.ttc<\/font>\n        <font weight="700" style="normal" index="25">NotoSansCJK.ttc<\/font>\n    <\/family>/};/^$/d' $MODPATH$FILEPATH$FILE >&2
+  fi
 else
-  ui_print "- Migration FAILED. Nothing have done to your system."
+  abort "! Migration FAILED. Nothing have done to your system."
 fi
 
 ui_print "- Setting permissions"
